# Generated by Django 5.2.1 on 2025-07-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.shutterstock.com/image-illustration/coming-soon-concept-image-text-600nw-2402613961.jpg', max_length=500),
        ),
    ]
